### PR TITLE
Pair programming results with Angie

### PR DESCRIPTION
**Pull request by ericxtang**
Angie and I did a pair session this morning on LPMS.  We updated the doc, fixed some bugs, and created a new simple media server.

CircleCI is failing on this, but not because of the code we checked in.  I think there are some existing failing tests.  @j0sh or @darkdarkdragon can you take a look?

### CODE REVIEW

**Comment by j0sh** [comment]
@ericxtang Not exactly sure why Circle was failing, as the code around those tests (the "external" files) was unused and hasn't seen development since 2017.

* Removed unused "external" files and related dependencies
* Removed outdated "RTMP segment packer" example program
* Minor update to the README

CircleCI takes a *long* time to run (nearly 20 minutes). Perhaps we could build a LPMS Docker container for Circle at some point. @darkdarkdragon any thoughts?

**Comment by darkdarkdragon** [comment]
@j0sh I thought about creating special docker image with FFmpeg for a long time. I'll do it as soon as @ericxtang will create special 'service' user on GitHub to link to docker hub account, so I can configure auto-building of all the Livepeer docker images on docker hub.
Plus looks like CircleCI config for this repo should be upgraded to new version.

**Comment by darkdarkdragon** [comment]
@j0sh Why do tests (in CircleCI) gets run inside go-livepeer repo?

**Comment by j0sh** [comment]
> Why do tests (in CircleCI) gets run inside go-livepeer repo?

Not sure, it's been that way for a long time. The Circle stuff needs to be updated anyway. Made an early attempt at it here:


```diff
commit 3add30c6e27adefc3f32ca088f14768ac277d720
Author: Josh Allmann <joshua.allmann@gmail.com>
Date:   Fri Feb 1 09:35:38 2019 -0800

    circle: Update to 2.0 config.

diff --git a/.circleci/config.yml b/.circleci/config.yml
new file mode 100644
index 0000000..fb064f1
--- /dev/null
+++ b/.circleci/config.yml
@@ -0,0 +1,86 @@
+# This configuration was automatically generated from a CircleCI 1.0 config.
+# It should include any build commands you had along with commands that CircleCI
+# inferred from your project structure. We strongly recommend you read all the
+# comments in this file to understand the structure of CircleCI 2.0, as the idiom
+# for configuration has changed substantially in 2.0 to allow arbitrary jobs rather
+# than the prescribed lifecycle of 1.0. In general, we recommend using this generated
+# configuration as a reference rather than using it in production, though in most
+# cases it should duplicate the execution of your original 1.0 config.
+version: 2
+jobs:
+  build:
+    working_directory: ~/livepeer/lpms
+    parallelism: 1
+    shell: /bin/bash --login
+    # CircleCI 2.0 does not support environment variables that refer to each other the same way as 1.0 did.
+    # If any of these refer to each other, rewrite them so that they don't or see https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables .
+    environment:
+      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
+      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
+      GOROOT: /usr/local/go
+      PATH: $PATH:$HOME/compiled/bin
+      PKG_CONFIG_PATH: $HOME/compiled/lib/pkgconfig
+    # In CircleCI 1.0 we used a pre-configured image with a large number of languages and other packages.
+    # In CircleCI 2.0 you can now specify your own image, or use one of our pre-configured images.
+    # The following configuration line tells CircleCI to use the specified docker image as the runtime environment for you job.
+    # We have selected a pre-built image that mirrors the build environment we use on
+    # the 1.0 platform, but we recommend you choose an image more tailored to the needs
+    # of each job. For more information on choosing an image (or alternatively using a
+    # VM instead of a container) see https://circleci.com/docs/2.0/executor-types/
+    # To see the list of pre-built images that CircleCI provides for most common languages see
+    # https://circleci.com/docs/2.0/circleci-images/
+    docker:
+    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
+      command: /sbin/init
+    steps:
+    # Machine Setup
+    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
+    # The following `checkout` command checks out your code to your working directory. In 1.0 we did this implicitly. In 2.0 you can choose where in the course of a job your code should be checked out.
+    - checkout
+    # Prepare for artifact and test results  collection equivalent to how it was done on 1.0.
+    # In many cases you can simplify this from what is generated here.
+    # 'See docs on artifact collection here https://circleci.com/docs/2.0/artifacts/'
+    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
+    # Dependencies
+    #   This would typically go in either a build or a build-and-test job when using workflows
+    # Restore the dependency cache
+    - restore_cache:
+        keys:
+        # This branch if available
+        - v1-dep-{{ .Branch }}-
+        # Default branch if not
+        - v1-dep-master-
+        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
+        - v1-dep-
+    # This is based on your 1.0 configuration file or project settings
+    - run: bash ./install_ffmpeg.sh
+    # This is based on your 1.0 configuration file or project settings
+    - run: mkdir -p "$HOME/.go_workspace/src/github.com/livepeer" && cd "$HOME/.go_workspace/src/github.com/livepeer" && rm -rf go-livepeer && git clone https://github.com/livepeer/go-livepeer
+    - run: cd $HOME/.go_workspace/src/github.com/livepeer && rm -rf lpms && go get -d github.com/livepeer/lpms/cmd/example && cd lpms && git fetch && git checkout $CIRCLE_BRANCH && git pull && go build cmd/example/*.go
+    # Save dependency cache
+    - save_cache:
+        key: v1-dep-{{ .Branch }}-{{ epoch }}
+        paths:
+        # This is a broad list of cache paths to include many possible development environments
+        # You can probably delete some of these entries
+        - ~/.go_workspace
+        # These cache paths were specified in the 1.0 config
+        - $HOME/.go_workspace/
+        - $HOME/nasm
+        - $HOME/x264
+        - $HOME/ffmpeg
+        - $HOME/compiled
+    # Test
+    #   This would typically be a build job when using workflows, possibly combined with build
+    # This is based on your 1.0 configuration file or project settings
+    - run: cd "$HOME/.go_workspace/src/github.com/livepeer/lpms" && bash test.sh
+    # Teardown
+    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
+    # Save test results
+    - store_test_results:
+        path: /tmp/circleci-test-results
+    # Save artifacts
+    - store_artifacts:
+        path: /tmp/circleci-artifacts
+    - store_artifacts:
+        path: /tmp/circleci-test-results
diff --git a/circle.yml b/circle.yml
deleted file mode 100644
index 2457dfe..0000000
--- a/circle.yml
+++ /dev/null
@@ -1,22 +0,0 @@
-machine:
-  environment:
-    GOROOT: /usr/local/go
-    PATH: $PATH:$HOME/compiled/bin
-    PKG_CONFIG_PATH: "$HOME/compiled/lib/pkgconfig"
-
-dependencies:
-  pre:
-    - bash ./install_ffmpeg.sh
-  cache_directories:
-    - "$HOME/.go_workspace/"
-    - "$HOME/nasm"
-    - "$HOME/x264"
-    - "$HOME/ffmpeg"
-    - "$HOME/compiled"
-  override:
-    - mkdir -p "$HOME/.go_workspace/src/github.com/livepeer" && cd "$HOME/.go_workspace/src/github.com/livepeer" && rm -rf go-livepeer && git clone https://github.com/livepeer/go-livepeer
-    - cd $HOME/.go_workspace/src/github.com/livepeer && rm -rf lpms && go get -d github.com/livepeer/lpms/cmd/example && cd lpms && git fetch && git checkout $CIRCLE_BRANCH && git pull && go build cmd/example/*.go
-
-test:
-  override:
-    - cd "$HOME/.go_workspace/src/github.com/livepeer/lpms" && bash test.sh
\ No newline at end of file
```

**Comment by j0sh** [comment]
Tried updating to Circle 2, but checkouts are failing with some [weird errors](https://circleci.com/gh/livepeer/lpms/218), so staying on Circle 1 for now. Tests still pass.

**Pull request merged**
