### PR TITLE
Second part of refactoring changes

### PR DESCRIPTION
**Pull request by MikeIndiaAlpha**
This set of changes is about two things:
- First, obvious follow-up to a first batch of changes, like removal of old transcode() function implementation, removing code that is no longer needed because only old transcode() used it, and so on and so forth
- Second, I was focusing on input/output sanitisation. The idea was to take bits and pieces of code that was scattered here and there, and slowly push it towards single open_input/close_input and open_output/close_output functions. It was surprisingly hard to achieve, and there were a lot of edge cases but it is done now. Justification for this approach was not only generic "make code better" angle of approach, but also a need to create groundwork for LL changes. Basically, if we are to plug into FFmpeg I/O internals it is so much easier to do if there is reasonable, single I/O flow to begin with.

### CODE REVIEW

**Review by cyberj0g — APPROVED** [review]
LGTM overall, great work @MikeIndiaAlpha!

It's a bit too large to review efficiently, hope we'll be able to make PRs in this part smaller from now on. I ran the tests on Linux x64 + Nvidia locally, hope someone could do it on Darwin as well (just in case, there shouldn't be any platform-related issues).

Minor nitpick, please reword or remove TODOs and pronounces from comments, since it's open source and visible for anyone. Maybe move some of longer and more useful explanations elsewhere. Options, which we used to store additional code-related details before, are:
1. Self-review comments in the PR
2. QUIRKS.md file in this repo
3. Github issues with appropriate tags

**Comment by MikeIndiaAlpha** [comment]
> LGTM overall, great work @MikeIndiaAlpha!
Thanks! I hope it will be downhill from now on.

> someone could do it on Darwin as well (just in case, there shouldn't be any platform-related issues).
You mean macOS, right? My primary development machine is MBP with Monterey and so I am testing on it. Unfortunately it is positively ancient, 2015 model so Intel not Apple silicon. But as you say, there shouldn't be platform related issues wrt my changes. Also tested on WSL2 on my other machine with Nvidia card. 

> Minor nitpick, please reword or remove TODOs and pronounces from comments, since it's open source and visible for 
> anyone. Maybe move some of longer and more useful explanations elsewhere. Options, which we used to store additional > code-related details before, are:
This is just the way I work, but you're right, it doesn't look pretty. Not that spaghetti code looks pretty :P

**Comment by chrishobcroft** [comment]
Hey, what is the status of this?

**Comment by cyberj0g** [comment]
It's an important piece of work addressing some of the tech debt in `lpms`. It's ready to be merged, but has no owner. One would need to make sure the tests are still passing with current version of `go-livepeer`, and then follow up in case of any unforeseen issues.

**Comment by chrishobcroft** [comment]
Hey, @MikeIndiaAlpha is there some way I can work with you to get this merged?

**Comment by MikeIndiaAlpha** [comment]
@chrishobcroft Sorry, I did this when I was employed by Livepeer and working on LPMS refactoring was my duty. I left the Livepeer around August last year, so you have to work with Livepeer team and not me. Good luck!

**Comment by j0sh** [comment]
Closing due to https://github.com/livepeer/lpms/pull/410

**Pull request closed without merging**
