### PR TITLE
ffmpeg: Properly flush filters / encoders after EOF.

### PR DESCRIPTION
**Pull request by j0sh**
Fixes some video skipping during playback
Fixes https://github.com/livepeer/lpms/issues/112
Maybe fixes https://github.com/livepeer/go-livepeer/issues/803

### CODE REVIEW

**Comment by j0sh** [comment]
@ericxtang Added a new fix  to this PR https://github.com/livepeer/lpms/pull/113/commits/6e45284c2204d2d6ce1963c20154d2f48d0b9946 that hopefully helps with https://github.com/livepeer/go-livepeer/issues/803 .

Could you test under the following scenarios and let me know if there are any audible issues with playback?
* Continuous playback via HLS (normal goclient usage)
* Standalone segment playback (curl a segment and play just that one back)

**Comment by ericxtang** [comment]
Checked both on my local and it seems good.  Thanks for everyone who dug into this :)

🚢

**Comment by j0sh** [comment]
This one wasn't quite ready for merging; there was still audio timestamp breakage with one of the samples in this repo.

**Comment by ericxtang** [comment]
Hmm... @j0sh are you referring to https://github.com/livepeer/lpms/issues/112?  I tested it and the problem seems to be fixed.  Which sample were you using?

**Comment by j0sh** [comment]
The issue happens with the LPMS transcoding sample: https://github.com/livepeer/lpms/blob/master/transcoder/test.ts 

Here is a test case exhibiting the results with some inline comments annotating the process. Note that the same case transcoded with the ffmpeg executable works OK, but the output timestamps are very different from the original source (whereas in LPMS we try to preserve the original timestamps as much as possible). This is probably a clue but needs further investigation.

```diff
diff --git a/ffmpeg/ffmpeg_test.go b/ffmpeg/ffmpeg_test.go
index f362db7..9b8e7dc 100644
--- a/ffmpeg/ffmpeg_test.go
+++ b/ffmpeg/ffmpeg_test.go
@@ -374,3 +374,51 @@ func TestTranscoder_Timestamp(t *testing.T) {
 	`
 	run(cmd)
 }
+
+func TestTranscoder_AudioPreroll(t *testing.T) {
+	// Ensure the transcoder drops audio preroll frames
+	run, dir := setupTest(t)
+	defer os.RemoveAll(dir)
+
+     // run segmenter on sample file 
+	err := RTMPToHLS("../transcoder/test.ts", dir+"/out.m3u8", dir+"/out_%d.ts", "1", 0)
+	if err != nil {
+		t.Error(err)
+	}
+     // transcode first two segments
+	err = Transcode(dir+"/out_0.ts", dir, []VideoProfile{P240p30fps16x9})
+	if err != nil {
+		t.Error(err)
+	}
+	err = Transcode(dir+"/out_1.ts", dir, []VideoProfile{P240p30fps16x9})
+	if err != nil {
+		t.Error(err)
+	}
+
+	cmd := `
+		set -eux
+		cd $0
+		ls -lha
+ # check last and first timestamps of original segments
+ffprobe -loglevel quiet -show_frames -select_streams a out_0.ts | grep pts= | head -1
+ffprobe -loglevel quiet -show_frames -select_streams a out_0.ts | grep pts= | tail -1
+ffprobe -loglevel quiet -show_frames -select_streams a out_1.ts | grep pts= | head -1
+
+ffprobe -loglevel quiet -show_frames -select_streams a out0out_0.ts | grep duration= | tail -1
+
+ # check last and first timestamps of transcoded segments. This is what's broken.
+ffprobe -loglevel quiet -show_frames -select_streams a out0out_0.ts | grep pts= | head -1
+ffprobe -loglevel quiet -show_frames -select_streams a out0out_0.ts | grep pts= | tail -1
+ffprobe -loglevel quiet -show_frames -select_streams a out0out_1.ts | grep pts= | head -1
+
+ # Transcode same segments with ffmpeg binary. This looks OK.
+ffmpeg -loglevel quiet -i out_0.ts -vn -c:a aac -ac 2 -sample_rate 44100 z0.ts
+ffprobe -loglevel quiet -loglevel quiet -show_frames -select_streams a z0.ts | grep pts= | tail -1
+ffmpeg -loglevel quiet -i out_1.ts -vn -c:a aac -ac 2 -sample_rate 44100 z1.ts
+ffprobe -loglevel quiet -show_frames -select_streams a z1.ts | grep pts= | tail -1
+
+		exit 1
+	`
+
+	run(cmd)
+}
```

**Comment by ericxtang** [comment]
I see.  Do you think this is likely a ffmpeg issue?  We could ear-mark this and come back to fix later.

**Comment by j0sh** [comment]
Can't say for certain without some investigation. Agreed that it can likely wait until later.

**Pull request merged**
